root = "."
tmp_dir = "/tmp"

[build]
  args_bin = [
    "--db-uri=postgres://ytrssil:ytrssil@localhost:5432/ytrssil?sslmode=disable",
    "--auth-token=foo",
    "--dev",
  ]
  entrypoint = "./dist/ytrssil"
  cmd = "make build"
  delay = 500
  exclude_dir = ["migrations", "bin"]
  exclude_file = []
  exclude_regex = ["_test\\.go", "_templ\\.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "templ"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[log]
  main_only = true
  time = false
  silent = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
