---
name: ytrssil
services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ytrssil
      POSTGRES_USER: ytrssil
      POSTGRES_DB: ytrssil
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 2s
      retries: 5

  api:
    image: theedgeofrage/ytrssil:api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_URI: "postgresql://ytrssil:ytrssil@postgres/ytrssil?sslmode=disable"
      PORT: "80"
    ports:
      - "8080:80"

  migrations:
    image: theedgeofrage/ytrssil:migrations
    restart: unless-stopped
    depends_on:
      - postgres
    command:
      - "-path=/migrations/"
      - "-database"
      - "postgresql://ytrssil:ytrssil@postgres/ytrssil?sslmode=disable"
      - "up"

volumes:
  postgres:
